Hackaton
Ser1ousSAM/Data_Bases pull request #2
Opened 2023-04-02 18:37 UTC by Ser1ousSAM

2023-04-02 18:51 UTC, Ser1ousSAM commented on server/hub.go
> +				case client.send <- message:
Мне ведь здесь нужно отправлять всем сообщение о запросе в базу? И здесь же вызывать горутину, которая будет отправлять инсерт в базу?

2023-04-02 19:00 UTC, Ser1ousSAM commented on server/data_Base.go
> +// А зачем мне интерфейс, если я буду только ивентами оперировать и только их передавать?
И к этому же вопросу ещё дополнительный.
Как заготовку сделать для запроса и как это протестировать?
Интерфейс же используется, если нам нужно с разными сущностями взаимодействовать, которые относятся к чему-то одному, но тут у нас только event и всё, поэтому не особо понимаю, зачем интерфейс.
P. S. По факту, в БД у нас только камера и событие есть и всё.

2023-04-03 12:30 UTC, RyabovNick requested changes
В целом тут мало что можно прокомментировать. Куски примеров без адаптации под свои нужды)

2023-04-03 12:30 UTC, RyabovNick commented on chat_exapmle/.idea/.gitignore
файлы IDE надо в .gitignore и не коммитить

2023-04-03 12:30 UTC, RyabovNick commented on server/hub.go
> +				case client.send <- message:
Тут всё-таки специфичная задача в примере - кто-то написал (broadcast - Inbound messages from the clients.)
это сообщение шлётся всем клиентам.

В твоей задаче это лишнее, просто структура Hub (без broadcast) должна быть доступна из http метода, который обрабатывает запросы http от нейронки. И там просто рассылка всем клиентам. 

Этот метод можно оставить и запустить в рутине чисто для управления подключеними/отключениями клиентов

2023-04-03 12:30 UTC, RyabovNick commented on server/main.go
> +	//как связать hub и data
просто handler делаешь методом hub

короткий пример: https://go.dev/play/p/zSr6BpYsShU

2023-04-03 12:30 UTC, RyabovNick commented on server/data_Base.go
> +	config, _ := pgx.ParseConfig("")
Прочитать про connection pool https://github.com/jackc/pgx/wiki/Getting-started-with-pgx

2023-04-03 12:30 UTC, RyabovNick commented on server/data_Base.go
> +// А зачем мне интерфейс, если я буду только ивентами оперировать и только их передавать?
Нет, go интерфейсы это про loose coupling в твоём приложении. И он создаётся там, где используется. 
Как пример использования надо изучить io.Reader, io.Writer стандартные интерфейсы

2023-04-06 19:09 UTC, RyabovNick requested changes

2023-04-06 19:09 UTC, RyabovNick commented on server/data_Base/data_Base.go
> +type DB_Sender interface {
Интерфейс создаётся там, где используется, а не там, где реализация

Материалов по теме много, но если надо - можно глянуть и то, что у меня было в прошлом году: https://www.youtube.com/watch?v=oF5joYEmzGg&list=PL4wpCvLmqD_TKIAmEmu4piCGWJFvzxXKh&index=5

2023-04-06 19:09 UTC, RyabovNick commented on server/data_Base/data_Base.go
> +	id          int
Скорее всего эта структура же потом куда-то отдаётся, думаю её атрибуты должны быть экспортируемые

2023-04-06 19:09 UTC, RyabovNick commented on server/hub.go
> +	response, err := client.Do(request)
Не очень понимаю, вроде запрос принимаешь, но при этом в коде наоборот - делаешь его?

2023-05-07 13:41 UTC, closed without merging