final task
Ser1ousSAM/Data_Bases pull request #6
Opened 2023-05-07 14:10 UTC by Ser1ousSAM

2023-05-10 17:43 UTC, RyabovNick commented
Сервис складского учёта

1.	Администратор. Добавление нового оператора, пользователя (работник склада)
2.	Оператор. Добавление нового поставщика в систему
3.	Оператор. Добавление нового товара в систему (название, вес, количество, объём, от кого) (Поставка товара)
4.	Оператор. Добавление информации по отгрузки товара (кому, что, сколько, когда) 
5.	Пользователь. Поиск товара
6.	Пользователь. Просмотр задач на сегодня (с поиском по различным параметрам, пагинацией)
7.	Оператор. Назначить задачу на пользователя
8.	Пользователь. Взять задачу в работу
9.	Администратор. Просмотр выполненных заказов (можно задать дату, id, поиск по названию поставщика, поиск по названию адресата доставка)
10.	Администратор. Блокировка оператора, пользователя.

2023-05-20 08:03 UTC, RyabovNick requested changes
Запросы ещё на каждый пункт

2023-05-27 08:17 UTC, Ser1ousSAM commented
Изменил немного init файл, чтобы в поставке определить поставщика и адресата

2023-05-31 16:40 UTC, RyabovNick approved these changes

2023-05-31 16:44 UTC, merged